config/routes.rb
Midashboard::Application.routes.draw do

  devise_for :users
  resources :users

  root to: 'dashboards#index'
  
  resources :dashboards

  resources :widgets

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :data_type, :description, :name, :root_uri, :title,
    :y_field, :y_label, :x_field, :x_label, :before_parameter, :after_parameter,
    :date_modifier, :x_times, :y_times, :x_points, :y_points, :chart_type,
    :y_compact_method, :x_compact_method

  DEFAULT_POINTS = 6
  DEFAULT_COMPACT_METHOD = 'first'
  DEFAULT_BEFORE_PARAMETER = 'before'
  DEFAULT_AFTER_PARAMETER = 'after'

  has_many :dashboard_widgets
  has_many :dashboards, through: :dashboard_widgets

  acts_as_indulgent

  validates :name, presence: true, uniqueness: true

  def raw
    @raw ||= ApiClient.new(uri).json
  end

  def uri
    @uri ||= URI(root_uri)
  end

  def before(time)
    add_to_query before_parameter => time_for_query(time)
  end

  def after(time)
    add_to_query after_parameter => time_for_query(time)
  end

  def time_for_query(time)
    date_modifier? ? time.strftime(date_modifier) : URI.escape(time.as_json)
  end

  def add_to_query(params)
    uri.query = (split_query + params.to_a).collect{|q| q.join('=')}.join('&')
  end

  def split_query
    unescaped_query.split('&').collect{|s| s.split('=')}
  end

  def unescaped_query
    uri.query ? URI.unescape(uri.query) : ""
  end

  def x_label
    first_or_human_second super, x_field
  end

  def y_label
    first_or_human_second super, y_field
  end

  def x_points
    super.blank? ? DEFAULT_POINTS : super
  end

  def y_points
    super.blank? ? DEFAULT_POINTS : super
  end

  def x_compact_method
    super.blank? ? DEFAULT_COMPACT_METHOD : super
  end

  def y_compact_method
    super.blank? ? DEFAULT_COMPACT_METHOD : super
  end

  def before_parameter
    super.blank? ? DEFAULT_BEFORE_PARAMETER : super
  end

  def after_parameter
    super.blank? ? DEFAULT_AFTER_PARAMETER : super
  end

  def title
    first_or_human_second super, name
  end

  def x_data
    @x_data ||= get_data_for(x_field, x_times?)
  end

  def y_data
    @y_data ||= get_data_for(y_field, y_times?)
  end

  def x_series
    @x_series ||= x_series_class.new(x_data)
  end

  def y_series
    @y_series ||= y_series_class.new(y_data)
  end

  def process_cell(entry, times)
    return parse_time(entry) if times
    return entry.to_f if numeric?(entry)
    entry
  end

  def numeric?(entry)
    return true if entry =~ /^\d+$/
    true if Float(entry) rescue false
  end

  def parse_time(entry)
    Time.parse(entry)
  rescue ArgumentError, TypeError
    entry
  end

  def data
    @data ||= build_data
  end

  private
  def build_data
    x_data.compact_to! y_data, x_compact_method
    y_data.compact_to! x_data, y_compact_method
    [x_data, y_data].transpose
  end

  def humanize(text)
    text.blank? ? "" : text.humanize
  end

  def first_or_human_second(first, second)
    first.blank? ? humanize(second) : first
  end

  def y_series_class
    y_times? ? TimeSeries : DataSeries
  end

  def x_series_class
    x_times? ? TimeSeries : DataSeries
  end

  def walkable_hash
    @walkable_hash ||= HashWalker.new(raw)
  end

  def get_data_for(field, is_time)
    Compactor.new walkable_hash.array(field).collect{|d| process_cell(d, is_time)}
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /widgets
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    @widget = Widget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget.data }
    end
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  def create
    @widget = Widget.new(params[:widget])


    if @widget.save
      redirect_to @widget, notice: 'Widget was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /widgets/1
  def update
    @widget = Widget.find(params[:id])

    if @widget.update_attributes(params[:widget])
      redirect_to @widget, notice: 'Widget was successfully updated.' 
    else
      render action: "edit"
    end

  end

  # DELETE /widgets/1
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy
    redirect_to widgets_url
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  
  def widget_chart(widget)
    holder_id = "widget_chart_#{widget.name}"
    holder = content_tag 'div', "", id: holder_id
    chart = chart_instance(widget).chart
    if chart.respond_to? :to_js
      chart = render_chart(chart , holder_id)
    end
    [holder, chart].join("\n").html_safe
  end
  
  def chart_instance(widget)
    chart_type = widget.chart_type? ? widget.chart_type : 'default'
    klass = BaseTable.chart_types[chart_type.to_sym] || BaseTable
    klass.new(widget)
  end

  def widget_table(widget)
    holder_id = "widget_table_#{widget.name}"
    holder = content_tag 'div', "", id: holder_id
    chart = render_chart BaseTable.new(widget).chart, holder_id
    [holder, chart].join("\n").html_safe
  end
  
end

app/views/widgets/_form.html.erb
<%= simple_form_for(@widget) do |f| %>
  <%= f.error_notification %>

  <div class="form_block">
    <%= f.input :name %>
    <%= f.input :title %>
    <%= f.input :root_uri %>
    <%#= f.input :data_type %>
    <%= f.input :chart_type, collection: BaseTable.chart_types.keys, prompt: 'Please select' %>
  </div>
  
   <div class="form_block"> 
    <%= f.input :before_parameter %>
    <%= f.input :after_parameter %>
    <%#= f.input :date_modifier %>
    <%= f.input :description, input_html: { rows: 3 } %>
   </div>
  
  <div class="form_block">  
    <%= f.input :y_field %>
    <%= f.input :y_label %>
    <%= f.input :y_times %>
    <%#= f.input :y_points %>
    <%= f.input :y_compact_method, collection: Compactor.compaction_methods.invert %>
  </div>

  <div class="form_block">
    <%= f.input :x_field %>
    <%= f.input :x_label %>
    <%= f.input :x_times %>
    <%#= f.input :x_points %>
    <%= f.input :x_compact_method, collection: Compactor.compaction_methods.invert %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<%= 
  content_tag(
    'p',
    link_to('New Widget', new_widget_path)
  ) if Widget.new.indulge?(current_user, :create)
%>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Chart</th>
    <th>Actions</th>
  </tr>

<% @widgets.each do |widget| %>
  <tr>
    <td><%= widget.name %></td>
    <td><%= widget.title %></td>
    <td><%= widget.chart_type %>
    <td>
      <%= link_to 'Show', widget %>
      <%= link_to(
            'Edit', edit_widget_path(widget)
          ) if widget.indulge?(current_user, :update) %>
      <%= link_to(
            'Destroy', 
            widget, 
            method: :delete, 
            data: { confirm: 'Are you sure?' } 
          ) if widget.indulge?(current_user, :delete)
      %>
    </td>
  </tr>
<% end %>
</table>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

app/views/widgets/show.html.erb
<h1>Widget: <%= @widget.name %></h1>

<%= widget_chart(@widget) %>

<%= widget_table(@widget) if @widget.chart_type? and @widget.chart_type != 'grid' %>

<%= link_to(
      'Edit', edit_widget_path(@widget)
    ) if @widget.indulge?(current_user, :update)
%>