config/routes.rb
Midashboard::Application.routes.draw do

  devise_for :users
  resources :users

  root to: 'dashboards#index'
  
  resources :dashboards

  resources :widgets

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  attr_accessible :description, :name, :title, :widget_ids

  has_many :dashboard_widgets, dependent: :destroy, uniq: true
  has_many :widgets, through: :dashboard_widgets, dependent: :destroy, uniq: true
  accepts_nested_attributes_for :widgets, allow_destroy: true
  
  has_many :dashboard_groups, uniq: true
  
  acts_as_indulgent
  
  validates :name, presence: true, uniqueness: true
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  before_filter :get_dashboard, only: [:show, :edit, :update, :destroy]
  before_filter :get_widgets, only: [:edit, :update, :create, :new]

  def index
    @dashboards = Dashboard.indulgence(current_user, :read)
  end

  def show
    @dashboard.widgets.each do |widget|
      widget.before(params[:before]) if params[:before]
      widget.after(params[:after]) if params[:after]
    end
  end

  def new
    @dashboard = Dashboard.new
  end

  def create
    @dashboard = Dashboard.new(params[:dashboard])
    if @dashboard.save
      redirect_to @dashboard, notice: 'Dashboard was successfully created.'
    else
      render action: "new"
    end
  end

  def edit

  end


  def update
    ensure_widget_ids_in_params
    if @dashboard.update_attributes(params[:dashboard])
      redirect_to @dashboard, notice: 'Dashboard was successfully updated.' 
    else
      render action: "edit"
    end
  end


  def destroy
    @dashboard.destroy
    redirect_to dashboards_url 
  end

  private
  def get_dashboard
    @dashboard = Dashboard.find(params[:id])
  end

  def get_widgets
    @widgets = Widget.all
  end

  def ensure_widget_ids_in_params
    params[:dashboard][:widget_ids] = [] unless params[:dashboard][:widget_ids]
  end


end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_filter.erb
<%= form_tag '', method: 'get', class: 'filter' do |f| %>

  <div class="input string optional">
    <%= label_tag 'after' %>
    <%= text_field_tag 'after', params[:after], class: 'datepicker' %>
  </div>

  <div class="input string optional">
    <%= label_tag 'before' %>
    <%= text_field_tag 'before', params[:before], class: 'datepicker' %>
  </div>

  <%= submit_tag 'filter', class: 'input' %>

<% end %>

app/views/dashboards/_form.html.erb
<%= simple_form_for(@dashboard) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :title %>
  <%= f.input :description, input_html: { rows: 3 } %>

  <%= f.association :widgets, as: :check_boxes %>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %>

app/views/dashboards/index.html.erb
<h1>Dashboards</h1>
<%= content_tag(
      'p', link_to('New Dashboard', new_dashboard_path)
    ) if Dashboard.new.indulge?(current_user, :create) %>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @dashboards.each do |dashboard| %>
  <tr>
    <td><%= dashboard.name %></td>
    <td><%= dashboard.title %></td>
    <td><%= dashboard.description %></td>
    <td>
      <%= link_to 'Show', dashboard %>
      <%= link_to(
            'Edit', edit_dashboard_path(dashboard)
          ) if dashboard.indulge?(current_user, :update) %>
      <%= link_to(
            'Destroy', 
            dashboard, 
            method: :delete, 
            data: { confirm: 'Are you sure?' }
          ) if dashboard.indulge?(current_user, :delete)
      %>
    </td>
  </tr>
<% end %>
</table>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

app/views/dashboards/show.html.erb
<h1><%= @dashboard.title %></h2>

<%= render 'filter' %>

<div>
  <%= @dashboard.description %>
</div>

<div class="widgets">
  <% @dashboard.widgets.each do |widget| %>
    <div class="widget">
      <%= link_to widget_chart(widget), widget_path(widget) %>
    </div>
  <% end %>
</div>

<%= link_to(
      'Edit', edit_dashboard_path(@dashboard)
    ) if @dashboard.indulge?(current_user, :update) 
%>